[abilityworks-webdisk]
type = webdav
url = https://test.abilityworks.com.au:2078/
vendor = other
user = ability-wp@test.abilityworks.com.au
pass-visible = Cc4ra240581!ability
pass = 3M-zT8ujh_fMiWOGWWzQ8wxdwp1eVgaPYg7Zj3ZCG-TkKZk
auth_redirect = true

[my-project]
type = alias
remote = abilityworks-webdisk:
