import 'slick-carousel/slick/slick.min.js'
import './jquery.multi-select/src/jquery.multi-select.js'

import './inc/global.js'
import './inc/titlebar.js'
import './inc/faqs.js'
import './inc/video-banner.js'
import './inc/member-info.js'
import './inc/latest.js'
import './inc/newsroom-search-results.js'
import './inc/articles.js'

import './inc/list-stories.js'
import './inc/list-toolkits.js'
import './inc/list-videos.js'
import './inc/story-details.js'
import './inc/resources.js'
import './inc/highlights.js'
import './inc/highlighted-video.js'

import './inc/video-carousel.js'
import './inc/multimedia-carousel.js'
import './inc/image-carousel.js'
import './inc/image-content-carousel.js'
import './inc/content-carousel.js'
import './inc/carousel-content.js'
import './inc/steps-carousel.js'

import './inc/caro-01.js'
import './inc/caro-02.js'
import './inc/caro-03.js'
import './inc/caro-07.js'
import './inc/caro-09.js'
import './inc/caro-10.js'
import './inc/caro-11.js'
import './inc/caro-12.js'
import './inc/caro-13.js'
import './inc/caro-14-15.js'
import './inc/caro-16.js'
import './inc/caro-17.js'
