import 'slick-carousel/slick/slick.min.js'
// import 'magnific-popup/dist/jquery.magnific-popup.min.js'
// import 'block-ui/jquery.blockUI.js'
// import './jquery.multi-select/src/jquery.multi-select.js'

import './inc/global.js'
import './inc/titlebar.js'
import './inc/faqs.js'
import './inc/video-banner.js'
import './inc/member-info.js'
import './inc/newsroom-search-results.js'
import './inc/latest.js'

import './inc/caro-01.js'
import './inc/caro-02.js'
import './inc/caro-03.js'
import './inc/caro-07.js'
import './inc/caro-09.js'
import './inc/caro-10.js'
import './inc/caro-11.js'
import './inc/caro-12.js'
import './inc/caro-13.js'
import './inc/caro-14-15.js'
import './inc/caro-16.js'
import './inc/caro-17.js'
import './inc/caro-18.js'
import './inc/caro-19.js'
import './inc/caro-20.js'
import './inc/caro-21.js'
