<?php
return array(
  'key' => 'layout_banner-intro',
  'name' => 'banner-intro',
  'label' => 'Banner - Intro',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f35069a817a1',
      'label' => 'Banner',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5f350678a74f1',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#f0f0ef',
    ),
    array(
      'key' => 'field_5f35069a817a2',
      'label' => 'Image',
      'name' => 'image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_5f35069a817a3',
      'label' => 'Mobile Image',
      'name' => 'mob_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_5f35069a817b3',
      'label' => 'Image width',
      'name' => 'image_width',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 100,
      'placeholder' => '',
      'prepend' => '',
      'append' => '%',
      'min' => 1,
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5f35069a817a4',
      'label' => 'Top Margin',
      'name' => 'top_margin',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'table',
      'sub_fields' => array(
        array(
          'key' => 'field_5f35069a817a5',
          'label' => 'Mobile',
          'name' => 'mobile',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 168,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817a6',
          'label' => 'Tablet',
          'name' => 'tablet',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 190,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817a7',
          'label' => 'Desktop',
          'name' => 'desktop',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 211,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817b2',
          'label' => 'Large Screen',
          'name' => 'large',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 360,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5f35069a817b4',
      'label' => 'Bottom Margin',
      'name' => 'btm_margin',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'table',
      'sub_fields' => array(
        array(
          'key' => 'field_5f35069a817b5',
          'label' => 'Mobile',
          'name' => 'mobile',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 50,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817b6',
          'label' => 'Tablet',
          'name' => 'tablet',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 75,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817b7',
          'label' => 'Desktop',
          'name' => 'desktop',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 90,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5f35069a817b8',
          'label' => 'Large Screen',
          'name' => 'large',
          'type' => 'number',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 100,
          'placeholder' => '',
          'prepend' => '',
          'append' => 'px',
          'min' => 0,
          'max' => '',
          'step' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5f35069a817a8',
      'label' => 'Intro',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5f35067269127',
      'label' => 'Display ReCap Home Button',
      'name' => 'recap_home_button_enabled',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array(
      'key' => 'field_5f35069a817a9',
      'label' => 'Icon',
      'name' => 'icon',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_5f35069c817c9',
      'label' => 'Secondary Icon',
      'name' => 'secondary_icon',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_5f35069a817aa',
      'label' => 'Title',
      'name' => 'title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f35069a817ab',
      'label' => 'Subtitle',
      'name' => 'subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f35069a817ac',
      'label' => 'Content',
      'name' => 'content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array(
      'key' => 'field_5f35069a817ad',
      'label' => 'Bottom Links',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5f35069d71af1',
      'label' => 'Layout',
      'name' => 'layout',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'row' => 'Row (horizontal)',
        'column' => 'Column (vertical)',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'default_value' => 'row',
      'layout' => 'horizontal',
      'return_format' => 'value',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_5f35069a817ae',
      'label' => 'Links',
      'name' => 'links',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5f35069a817af',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Link',
      'sub_fields' => array(
        array(
          'key' => 'field_5f35069a817af',
          'label' => 'Label',
          'name' => 'label',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '35',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f35069a817b0',
          'label' => 'URL',
          'name' => 'url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '40',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f35069a817b1',
          'label' => 'Open in new tab?',
          'name' => 'open_in_new_tab',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '10',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Yes',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array(
          'key' => 'field_5f35069a81ca8',
          'label' => 'Style',
          'name' => 'style',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '15',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'text' => 'Default (Text)',
            'fill-round' => 'Filled Round',
            'outline-round' => 'Outlined Round',
            'fill-round-2' => 'Secondary Filled Round',
          ),
          'default_value' => 'text',
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'return_format' => 'value',
          'ajax' => 0,
          'placeholder' => '',
        ),
      ),
    ),
  ),
  'min' => '',
  'max' => '',
);
