<?php
return array(
  'key' => 'layout_comm-activities',
  'name' => 'comm-activities',
  'label' => 'Community Activities',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f35069a8c911',
      'label' => 'Background Image',
      'name' => 'bg_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'min' => '',
  'max' => '',
);
