<?php
return array(
  'key' => 'layout_content',
  'name' => 'content',
  'label' => 'Content',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f0ff67c4ecba',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#ffffff',
    ),
    // array(
    //   'key' => 'field_5f0ff67c4ecbc',
    //   'label' => 'Light Mode',
    //   'name' => 'light_mode',
    //   'type' => 'true_false',
    //   'instructions' => '',
    //   'required' => 0,
    //   'conditional_logic' => 0,
    //   'wrapper' => array(
    //     'width' => '',
    //     'class' => '',
    //     'id' => '',
    //   ),
    //   'message' => 'Set text color white (for dark background)',
    //   'default_value' => 0,
    //   'ui' => 1,
    //   'ui_on_text' => '',
    //   'ui_off_text' => '',
    // ),
    array(
      'key' => 'field_5f0ff2c79956b',
      'label' => 'Content',
      'name' => 'content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
    ),
    array(
      'key' => 'field_5f322c8ff3c14',
      'label' => 'Width',
      'name' => 'width',
      'type' => 'number',
      'instructions' => 'Custom width on desktop, default is 100%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => 'Accept value in between 1-100',
      'prepend' => '',
      'append' => '%',
      'min' => 1,
      'max' => 100,
      'step' => '',
    ),
  ),
  'min' => '',
  'max' => '',
);
