<?php
return array(
  'key' => 'layout_content-content',
  'name' => 'content-content',
  'label' => 'Content - Content',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f35067bd2d10',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#ffffff',
    ),
    array(
      'key' => 'field_5f35067bd2d0f',
      'label' => 'Light Mode',
      'name' => 'light_mode',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'Set text color white (for dark background)',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array(
      'key' => 'field_5f35069ea741a',
      'label' => 'Align Items',
      'name' => 'align_items',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'flex-start' => 'Start',
        'center' => 'Center',
        'flex-end' => 'End',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'default_value' => 'flex-start',
      'layout' => 'horizontal',
      'return_format' => 'value',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_5f35067bd2d11',
      'label' => 'Left Content',
      'name' => 'left_content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
    ),
    array(
      'key' => 'field_5f35067bd2d12',
      'label' => 'Right Content',
      'name' => 'right_content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
    ),
  ),
  'min' => '',
  'max' => '',
);
