<?php
return array(
  'key' => 'layout_highlights',
  'name' => 'highlights',
  'label' => 'Highlights',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f1a5a8a91281',
      'label' => 'Title',
      'name' => 'title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f1a5a8a91282',
      'label' => 'Subtitle',
      'name' => 'subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f1a5a8a91288',
      'label' => 'Post Type',
      'name' => 'post_type',
      'type' => 'radio',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'post' => 'Resources',
        'pxa-comm-activity' => 'Community Recovery Activities',
        'pxa-comm-story' => 'Community Stories',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'default_value' => 'post',
      'layout' => 'horizontal',
      'return_format' => 'value',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_5f1a5a8a91283',
      'label' => 'Resources',
      'name' => 'resources',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a8a91288',
            'operator' => '==',
            'value' => 'post',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'post',
      ),
      'taxonomy' => '',
      'filters' => array(
        0 => 'search',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array(
      'key' => 'field_5f1a5a8a91289',
      'label' => 'Community Recovery Activities',
      'name' => 'activities',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a8a91288',
            'operator' => '==',
            'value' => 'pxa-comm-activity',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'pxa-comm-activity',
      ),
      'taxonomy' => '',
      'filters' => array(
        0 => 'search',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array(
      'key' => 'field_5f1a5a8a9128a',
      'label' => 'Community Stories',
      'name' => 'stories',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a8a91288',
            'operator' => '==',
            'value' => 'pxa-comm-story',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'pxa-comm-story',
      ),
      'taxonomy' => '',
      'filters' => array(
        0 => 'search',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array(
      'key' => 'field_5f1a5a8a91284',
      'label' => 'Right Links',
      'name' => 'links',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5f1a5a8a91285',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Link',
      'sub_fields' => array(
        array(
          'key' => 'field_5f1a5a8a91285',
          'label' => 'Label',
          'name' => 'label',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '40',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f1a5a8a91286',
          'label' => 'URL',
          'name' => 'url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f1a5a8a91287',
          'label' => 'Open in new tab?',
          'name' => 'open_in_new_tab',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '10',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Yes',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5f350678127a3',
      'label' => 'Auto scroll',
      'name' => 'auto_scroll',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'Set carousel to be auto scroll',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
  ),
  'min' => '',
  'max' => '',
);
