<?php
return array(
  'key' => 'layout_image-content-carousel',
  'name' => 'image-content-carousel',
  'label' => 'Image & Content Carousel',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f350698a731c',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#f0f0ef',
    ),
    array(
      'key' => 'field_5f3506cc8a194',
      'label' => 'Play Icon Color',
      'name' => 'play_icon_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#196281',
    ),
    array(
      'key' => 'field_5f3506cc8a190',
      'label' => 'Items',
      'name' => 'items',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5f3506cc8a191',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add item',
      'sub_fields' => array(
        array(
          'key' => 'field_5f3506cc8a191',
          'label' => 'Image',
          'name' => 'image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5f3506cc8a192',
          'label' => 'Play Video',
          'name' => 'video',
          'type' => 'oembed',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'width' => '',
          'height' => '',
        ),
        array(
          'key' => 'field_5f3506cc8a193',
          'label' => 'Description',
          'name' => 'description',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
      ),
    ),
  ),
  'min' => '',
  'max' => '',
);
