<?php
return array(
  'key' => 'layout_phase-links',
  'name' => 'phase-links',
  'label' => 'Phase Links',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f35068a71931',
      'label' => 'Headline',
      'name' => 'headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f35068a71932',
      'label' => 'Links',
      'name' => 'links',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5f35068a71934',
      'min' => 0,
      'max' => 2,
      'layout' => 'row',
      'button_label' => 'Add Link',
      'sub_fields' => array(
        array(
          'key' => 'field_5f35068a71933',
          'label' => 'Icon',
          'name' => 'icon',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5f35068a71934',
          'label' => 'Title',
          'name' => 'title',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '40',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f35068a71935',
          'label' => 'Subtitle',
          'name' => 'subtitle',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '40',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f35068a71936',
          'label' => 'URL',
          'name' => 'url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        // array(
        //   'key' => 'field_5f35068a71937',
        //   'label' => 'Open in new tab?',
        //   'name' => 'open_in_new_tab',
        //   'type' => 'true_false',
        //   'instructions' => '',
        //   'required' => 0,
        //   'conditional_logic' => 0,
        //   'wrapper' => array(
        //     'width' => '10',
        //     'class' => '',
        //     'id' => '',
        //   ),
        //   'message' => 'Yes',
        //   'default_value' => 0,
        //   'ui' => 0,
        //   'ui_on_text' => '',
        //   'ui_off_text' => '',
        // ),
      ),
    ),
  ),
  'min' => '',
  'max' => '',
);
