<?php
return array(
  'key' => 'layout_resources',
  'name' => 'resources',
  'label' => 'Resources',
  'display' => 'block',
  'sub_fields' => array(
    array(
      'key' => 'field_5f1a5a817c172',
      'label' => 'General',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5f350698a763e',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#f0f0ef',
    ),
    array(
      'key' => 'field_5f1a5a817c1f1',
      'label' => 'Background Image',
      'name' => 'bg_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_5f1a5a817c170',
      'label' => 'Title',
      'name' => 'title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5f1a5a817c174',
      'label' => 'Right Links',
      'name' => 'links',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5f1a5a817c175',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Link',
      'sub_fields' => array(
        array(
          'key' => 'field_5f1a5a817c175',
          'label' => 'Label',
          'name' => 'label',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '40',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f1a5a817c176',
          'label' => 'URL',
          'name' => 'url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f1a5a817c177',
          'label' => 'Open in new tab?',
          'name' => 'open_in_new_tab',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '10',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Yes',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5f1a5a817c173',
      'label' => 'Resources Listing',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5f1a5a817c171',
      'label' => 'Carousel',
      'name' => 'is_carousel',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'Show resources in carousel mode at initiate (resources selection required)',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array(
      'key' => 'field_5f1a5a817c178',
      'label' => 'Resources',
      'name' => 'resources',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a817c171',
            'operator' => '==',
            'value' => 1,
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'post',
      ),
      'taxonomy' => '',
      'filters' => array(
        0 => 'search',
        // 1 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array(
      'key' => 'field_5f1a5a8ca841a',
      'label' => 'Default Phase',
      'name' => 'default_phase',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a817c171',
            'operator' => '==',
            'value' => 0,
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'pxa-phase',
      'field_type' => 'select',
      'allow_null' => 1,
      'add_term' => 0,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
    ),
    array(
      'key' => 'field_5f1a5a8ca8a91',
      'label' => 'Items per page',
      'name' => 'posts_per_page',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5f1a5a817c171',
            'operator' => '==',
            'value' => 0,
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 8,
      'placeholder' => '',
      'prepend' => '',
      'append' => '%',
      'min' => 1,
      'max' => '',
      'step' => '',
    ),
  ),
  'min' => '',
  'max' => '',
);
