<?php
return array(
  'key' => 'layout_5f055a1d570d8',
  'name' => 'spacer',
  'label' => 'Spacer',
  'display' => 'table',
  'sub_fields' => array(
    array(
      'key' => 'field_5f056063bde02',
      'label' => 'Background Color',
      'name' => 'bg_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#ffffff',
    ),
    array(
      'key' => 'field_5f055fffbddff',
      'label' => 'Mobile Height',
      'name' => 'height_sm',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 20,
      'placeholder' => '',
      'prepend' => '',
      'append' => 'px',
      'min' => 0,
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5f05603dbde00',
      'label' => 'Tablet Height',
      'name' => 'height_md',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 30,
      'placeholder' => '',
      'prepend' => '',
      'append' => 'px',
      'min' => 0,
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5f05604fbde01',
      'label' => 'PC Height',
      'name' => 'height_lg',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 40,
      'placeholder' => '',
      'prepend' => '',
      'append' => 'px',
      'min' => 0,
      'max' => '',
      'step' => '',
    ),
  ),
  'min' => '',
  'max' => '',
);
